"""empty message

Revision ID: c34ad1c45acf
Revises: 3e09224a8480
Create Date: 2019-07-12 15:24:47.205566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34ad1c45acf'
down_revision = '3e09224a8480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('picture', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'picture')
    # ### end Alembic commands ###
